---
apiVersion: v1 
kind: Template
metadata:
  name: oso-evg-query 
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      template: oso-evg-query
    name: "oso-${PLAT}-ops-base"
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "oso-${PLAT}-ops-base:latest"
    postCommit: {}
    resources: {}
    source:
      contextDir: "docker/oso-ops-base/${PLAT}"
      git:
        ref: prod 
        uri: https://github.com/openshift/openshift-tools
      secrets: []
      type: Git
    strategy:
      dockerStrategy:
        env:
        - name: OO_PAUSE_ON_BUILD
          value: "false"
        from:
          kind: ImageStreamTag
          name: "${PLAT}:latest"
        noCache: true
      type: Docker
    triggers:
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      template: oso-evg-query
    name: oso-evg-query
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "oso-${PLAT}-evg-query:latest"
    postCommit: {}
    resources: {}
    source:
      contextDir: "docker/oso-evg-query/${PLAT}"
      git:
        ref: prod
        uri: https://github.com/openshift/openshift-tools
      secrets: []
      type: Git
    strategy:
      dockerStrategy:
        env:
        - name: OO_PAUSE_ON_BUILD
          value: "false"
        from:
          kind: ImageStreamTag
          name: "oso-${PLAT}-ops-base:latest"
      type: Docker
    triggers:
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      template: oso-evg-query
    name: "${PLAT}"
  spec:
    dockerImageRepository: "library/${PLAT}"
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: "registry.access.redhat.com/${PLAT}:latest"
      importPolicy: {}
      name: latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      template: oso-evg-query
    name: "oso-${PLAT}-ops-base"
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: "library/oso-${PLAT}-ops-base:latest"
      importPolicy: {}
      name: latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      template: oso-evg-query
    name: "oso-${PLAT}-evg-query"
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: "library/oso-${PLAT}-evg-query:latest"
      importPolicy: {}
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      template: oso-evg-query
    name: oso-evg-query
  spec:
    replicas: 1
    selector:
      deploymentconfig: oso-evg-query
    strategy:
      resources: {}
      type: Rolling
    template:
      metadata:
        labels:
          deploymentconfig: oso-evg-query
      spec:
        containers:
        - env:
          - name: OO_PAUSE_ON_START
            value: "false"
          image: "oso-evg-query/oso-${PLAT}-evg-query:latest"
          imagePullPolicy: Always
          name: oso-evg-query
          resources: {}
          securityContext:
            privileged: true
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /secrets
            name: oso-evg-query-secrets
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        serviceAccount: evgquery
        serviceAccountName: evgquery
        terminationGracePeriodSeconds: 30
        volumes:
        - name: oso-evg-query-secrets
          secret:
            secretName: oso-evg-query-secrets
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - oso-evg-query
        from:
          kind: ImageStreamTag
          name: "oso-${PLAT}-evg-query:latest"
      type: ImageChange
parameters:
- description: Platform name
  name: PLAT
  value: rhel7
- description: Project name
  name: NAMESPACE
  value: openshift-evg-query
